AWSTemplateFormatVersion: 2010-09-09
Description: >-
  foo-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Connectors:
      WriteAccessConn:
        Properties:
          Destination:
            - Id: SampleTable
            - Id: SampleTable2
            - Id: SampleTable3
            - Id: SampleSQS1
            - Id: SampleSQS2
            - Id: SampleBucketA
            - Id: SampleBucketB
          Permissions:
            - Write
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET


#     ___                                     ___  ___     
#    /   \_   _ _ __   __ _ _ __ ___   ___   /   \/ __\___ 
#   / /\ / | | | '_ \ / _` | '_ ` _ \ / _ \ / /\ /__\// __|
#  / /_//| |_| | | | | (_| | | | | | | (_) / /_// \/  \__ \
# /___,'  \__, |_| |_|\__,_|_| |_| |_|\___/___,'\_____/___/
#         |___/                                            


  SampleTable2:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  SampleTable3:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

#  __    ____  __    
# / _\  /___ \/ _\   
# \ \  //  / /\ \    
# _\ \/ \_/ / _\ \   
# \__/\___,_\ \__/   
                   
  SampleSQS1:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: "poc-queue-1"

  SampleSQS2:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: "poc-queue-2"

#  __ _____ 
# / _\___ / 
# \ \  |_ \ 
# _\ \___) |
# \__/____/ 
          
  SampleBucketA:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "foo-poc-bucket-a"

  SampleBucketB:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "foo-poc-bucket-b"